#!/bin/sh
set -e

SRC=$(pwd)
cd "$AUTOPKGTEST_TMP"

cmake "$SRC/examples/map_cli"
make

m() { echo "$*"; ./map_cli file persistent "$@" | tee -a log; }

m insert 1 1
m get 1
m insert 1 2
m get 1
m insert 2 10
m print
m remove 1
m get 1
m insert 1 3
m print

diff log - <<END
1
2
map[1] = 2
map[2] = 10
2
key not found
map[1] = 3
map[2] = 10
END
